language: java
jdk:
- oraclejdk8
env:
  global:
  - ACTIVATOR_VERSION=1.3.7
  - ACTIVATOR_ZIP_FILE=typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - ACTIVATOR_ZIP_URL=http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/${ACTIVATOR_ZIP_FILE}
  - PLAY2_HOME=${TRAVIS_BUILD_DIR}/activator-${ACTIVATOR_VERSION}-minimal
  - SBT_EXECUTABLE_NAME=activator
  - GH_REF=github.com/theAgileFactory/dbmdl-framework
  - secure: NQT/pa6Y2k4B+wrmUyYG671NeR46H6P8zGF8WZbtOjX5Yus3kmaZwOL1QQxu7UGPF1XyfUKfMWcQDhLJW4z9wgtEyyAucO4y/u4FmsmObPMfKRodEiTfnrr6CQx+gG7VMMfZxpgUWBkKnThULIHseNx6xZDvFsKVcaSheVGpYu8ktU9bGI1s5GqslJZPEG7wSyszTmiwMksHEGZlsDA6dNoaNssi1lbo/A9vKqEVEP+2Ba0P8Wq6iHmA1y/mMUGFLgL99gAHKD9iARzg/wPuiin1ppNzBpK0Fa5s07Vi2zP23fjHwT1LeyQ1Eqdk3YDO/pamacY/VEZb6QGsyaTqUmZLRAw+eg+lZRxUOdO6JRkadi3WjmbU1Gwyj6PGBDJg4+Lr4ZT9Y/3pQbgehwuYoTLyYZrMKXsb0LQ0ERl0Yke3PzoMsGizPHJULMyUMBXpzU5jZUFuPHNbtDbN0m2KvbsLJHlG/CWSjxwPFPOES6qZL1cJU4Gj/k1fyj0CdRN5OvK8qdekOmJdgYS18F3JPXXIMhbsdFxbGvW8WaZ9JF144DF23tI2FHnjbQauX6pt250LzR/IxKCrASBCrdkSWkHfDzGRO+gi9EDm7xxsQvmVYadv1VW91u3k4agowy/lYMVoidYh1blhjxIP4aRGX9wsJZhMQFplDskHCo4oH/Q=
  - secure: dVaojZy0u660xYbIgOUZS/WnGsJkOMjvFoMiH61BJyeaU5Y+PsUFZRnmYsY4EWYBD4ftIf+jy47TLVXYYrmgaqfwzdS2fwJgzdpNJbABv5O9XJGSXXV1y/7/Z0VMeTJILPhLDzQPvtnEXJLue+aVHgFQifJ7WzNc7+/GtcWynUKGr+SGn/SpI6tMg2ByLoAapHT+aDlc4o5qfV8pZ0bMQgbFjeb8RlXX/dgXnWbyVt34llheni+SaqudBLIZApHjjOUY/kdH2UZlGu6ghV2SuFyYT6h77VOz02wFPFgyiQbTz4/c+Z7C5039XMpyq16hRbvlG6SrUngY0fVyTcF0as+al9AZnLd0TiPGLek8CnB+II9O9zNWp35/40se6dSrdoO0bUiNBJbk7hlLUcFQUeOXvaD74XWZthzdX4KZXKqUO8IGRzLW/4Q36dOb76AGLW7w1o5huPimaWydDzlmk5d2gmKPPXHXvmRwWD5TY3krXxCHqMqvJFcgS3XJ2fcFnGIFYkGgwXhkbkQBZ82otHGpsp4DCNfkmA/cuIw3A04qkQF0tCelpjhckUcOCO4w4UcSTZcOor01iwmhLCMG7NyJEjptr4+EP1oCjcDgGrSsBXcggNpJYzo5qJoc4ID4YwDt7//B4Fsfn+CzRwPMSDS2djXO+/md+wXTWereZf4=
  - secure: Viqcsp50+XI2ZC5/+9VJUtls8yInnnSInc/iIZpVA1oeahClgjhcR4AhRic+riVaQLiZk+bdg7UUnp1EThotLFSrgCbkTSk5II5fIU20xsM6zlfWzQG+j8lfiPOyWlB9fzGdUCI99POdPmDQMSKPN7pnnEwfZlZNIZwIMPxf54ruhr8w9lvv4L4E/GGdSHfDIe8CYT69R1xIkXh/gh4t+7bmjpmh73ih2PYh3MxPW3y6KG9tLwNYgNbhJKEXu/1og+GtMotAiAQp+T0vofb7Fsb3h1LzbfsBTigdqpUwn+PWkgtnlJKaCBafm0pGZn05EOEbVLP+/DNijYn+ol+XSpghHjod78hjK6pk0xLmxoEY1xTDsjaoilu6RAkEKdN/B2NLokucnM1Z4tqopimbL0SIs5PB7vljz6hDq9tm5+BvXzFmJjvZe+ZRB9Jy5J20f3rYv91v5JVNREcx3hMvpH5vuNA0I3iszx7w0ffxqYjKCC4Nns9lFSema+XDeRGwv+QQR5NG9E/mTTLr2GChGOyVSA/QTOhDFr+eoHWmKQIeqMof+bIOC8psfODkePIhyeTtzB/thIanwpNza1wmKY23CKzDHFdGJXYqVMEYbiwSQolLJXg/h9HVzcAoX93S+qJM8Xc9I1RAdtBoXfm8ocBjJMs/V8xRHthPizaQXbA=
  - secure: q18ehdKmYgx1FW8KQ4LjEc06gM68nElBySBZlslmIgWqmrQiMqUVzNQramwEVmTRn/Z3ulB4bNvkqF3e5sStEQlMhzC2Uhr/lwGAhwuFp8zkQ6QSSS4LE54KOkwtC/Jw1QBJDjqr964rz3efGwGqqqtdKnOcSmM+8bSKeys8SYG3W2X/EHIscS5q/cRlXA7sWV5+S5uwOie/RXtgsoL98+te2/VofpjygoTuOJZ9iJ+mp0atqkuFXmpniK6nRQMWoHsBtXZoJyW/m1r1hGWtc2nKChUBJPJLkonsdoNpVg6iSGDvqeo2ShJXza5q5ox79bQ6OlltIZPF3x0OZer1Iz41sQqzhCu4LSjVL1yTw/zlxIrceovM4pgoUrLptF9hvQ5CQFD+itetEjr2TgB5jR1M/NkaygkTqnOS8m2gcoT606lEI6WLZp23Ux1cb//OW1JFD896eTTkafrYc8uiUUc3WbNf0HITObjSYvrpY8DsE8rup6HSgwQyqpkkK6+Nw2ziOP39kCVpQ/C7FKhlvJLbTBNP4emc3+Js6+JimHVLKBeMpRVfgQrVbWxIuTHNgUJBMstxQv7tG8pg/mlnohnDitlFhpgOAwJf6lxHVGDa96Ns0Tdm86fNlseHRSwu2ci+JYJ1j0rcwWGrX+5JPO0ZE9od9y7LsTeIItL9CcI=
before_install:
- sudo apt-get update
- sudo apt-get install --only-upgrade -y oracle-java8-installer
- mkdir -p ~/.gnupg
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out ~/.gnupg/secring.gpg
  -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.gpg.enc -out ~/.gnupg/pubring.gpg
  -d
- echo "<settings><servers><server><id>ossrh</id><username>\${OSSRH_JIRA_USERNAME}</username><password>\${OSSRH_JIRA_PASSWORD}</password></server></servers></settings>"
  > ~/.m2/settings.xml
install:
- wget ${ACTIVATOR_ZIP_URL}
- unzip -q ${ACTIVATOR_ZIP_FILE}
script:
- mvn clean install -Dgpg.passphrase="${GPG_PASSPHRASE}" --settings ~/.m2/settings.xml
after_success:
- .travis/deploy.sh
after_script:
- rm ~/.gnupg/secring.gpg
- rm ~/.gnupg/pubring.gpg
- rm ~/.m2/settings.xml
notifications:
  email: true
branches:
  only:
  - master
  - R16.2.3
scala:
- 2.11.8
cache:
  directories:
  - .autoconf
  - ~/.m2
  - ~/.sbt
  - ~/.ivy
